In [2]:
# !pip install joblib

  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)


In [3]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
 
plt.style.use('fivethirtyeight')

In [13]:
class Perceptron:
    def __init__(self,eta: float=None,epochs: int=None):
        self.weights=np.random.randn(3)* 1e-4
        self.eta=eta #learning rate
        self.epochs=epochs #iterations
        
    def fit(self,X,y):
        self.X=X
        self.y=y
        
        X_with_bias=np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X with bias \n {X_with_bias}")
        

In [14]:
obj=Perceptron(eta=0.01,epochs=10)

In [15]:
obj.eta

0.01

In [16]:
obj.epochs

10

In [17]:
obj.weights

array([-1.32290120e-05,  1.02640634e-04, -6.19381764e-05])

In [19]:
X=np.ones((4,2))
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
y=np.ones((4,1))
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [21]:
obj.fit(X,y)

X with bias 
 [[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
